/* =========================================
   CAREBRIDGE — SHARED APP LOGIC
========================================= */

const T = {
en:{
 side_dashboard:"Dashboard",
 side_patients:"Patients",
 side_triage:"Triage",
 side_referrals:"Referrals",
 side_followups:"Follow-ups",
 stat_todaypatients:"TODAY'S PATIENTS",
 stat_triagepending:"TRIAGE PENDING",
 stat_activereferrals:"ACTIVE REFERRALS",
 stat_followupsdue:"FOLLOW-UPS DUE",
 sec_patientqueue:"PATIENT QUEUE",
 sec_todaypatients:"Today's Patients",
 sec_digitaltriage:"DIGITAL TRIAGE",
 sec_quickassess:"Quick Assessment (IMNCI-referenced)",
 sec_referraltracking:"REFERRAL TRACKING",
 sec_closedloop:"Closed-Loop Referrals",
 col_patient:"Patient",
 col_patientid:"Patient ID",
 col_age:"Age",
 col_triage:"Triage",
 col_action:"Action",
 sym_breathing:"Difficulty breathing",
 sym_chestpain:"Severe chest pain",
 sym_fever:"High fever",
 sym_headache:"Mild headache",
 field_ops:"FIELD OPERATIONS",
 good_morning:"Good morning, Sunita",
 manage_desc:"Manage patient registration, triage and referrals — works offline.",
 brand_asha:"ASHA / ANM Workspace",
 district_monitoring:"District Health Monitoring",
 doctor_workspace:"Doctor Workspace",
 facility_admin:"Facility Administration",
 patient_portal_label:"Patient Portal",
 dashboard:"Dashboard",
 overview:"Overview",
 facilities:"Facilities",
 referral_network:"Referral Network",
 alerts:"Alerts",
 trends:"Trends",
 patient_queue:"Patient Queue",
 patient_records:"Patient Records",
 diagnostics:"Diagnostics",
 staff:"Staff",
 medicine:"Medicine",
 reports:"Reports",
 my_records:"My Records",
 appointments:"Appointments",
 medicines:"Medicines",
 clinical_workspace:"CLINICAL WORKSPACE",
 doctor_dashboard:"Doctor Dashboard",
 doctor_desc:"Review patients, clinical history and active referrals.",
 clinical_active:"Clinical System Active",
 facility_operations:"FACILITY OPERATIONS",
 facility_desc:"Real-time overview of facility operations — controlled by facility admin.",
 operational:"Operational",
 district_health_monitoring:"DISTRICT HEALTH MONITORING",
 district_desc:"Monitor healthcare continuity across connected facilities.",
 network_operational:"Network Operational",
 patient_overview:"PATIENT OVERVIEW",
 patient_good_morning:"Good morning, Vaishali",
 patient_desc:"Here's an overview of your current healthcare journey.",
 connected:"Connected",
 today:"Today",
 connected_facilities:"CONNECTED FACILITIES",
 patients_today:"PATIENTS TODAY",
 high_risk_cases:"HIGH-RISK CASES",
 across_district:"Across the district",
 across_facilities:"Across facilities",
 currently_tracked:"Currently tracked",
 under_monitoring:"Under monitoring",
 referral_completion:"REFERRAL COMPLETION",
 followup_completion:"FOLLOW-UP COMPLETION",
 triage_coverage:"TRIAGE COVERAGE",
 attention_required:"ATTENTION REQUIRED",
 priority_alerts:"Priority Alerts",
 waiting_patients:"WAITING PATIENTS",
 red_priority:"RED PRIORITY",
 referrals:"REFERRALS",
 completed:"COMPLETED",
 immediate_attention:"Immediate attention",
 consultations_today:"Today's consultations",
 active_today:"Active today",
 clinical_queue:"CLINICAL QUEUE",
 patients_awaiting_review:"Patients Awaiting Review",
 priority:"Priority",
 reason:"Reason",
 open_record:"Open Record",
 diagnostic_coordination:"DIAGNOSTIC COORDINATION",
 requested_tests:"Requested Tests",
 test:"Test",
 status:"Status",
 pending:"Pending",
 in_progress:"In Progress",
 blood_cbc:"Blood CBC",
 xray_chest:"X-Ray Chest",
 referral_management:"REFERRAL MANAGEMENT",
 active_referrals_closed:"Active Referrals (Closed-Loop)",
 active_queue:"ACTIVE QUEUE",
 patients_waiting:"Patients waiting",
 pending_referrals:"PENDING REFERRALS",
 awaiting_completion:"Awaiting completion",
 require_monitoring:"Require monitoring",
 referral_status:"Referral Status",
 sent:"SENT",
 accepted:"ACCEPTED",
 arrived:"ARRIVED",
 completed_upper:"COMPLETED",
 facility_queue:"FACILITY QUEUE",
 department_overview:"Department Overview",
 department:"Department",
 waiting:"Waiting",
 doctors:"Doctors",
 normal:"Normal",
 busy:"Busy",
 high_load:"High Load",
 medicine_availability:"MEDICINE AVAILABILITY",
 facility_stock:"Facility Stock",
 qty:"Qty",
 facility_controlled:"FACILITY-CONTROLLED",
 staff_roster:"Staff Roster & Attendance",
 name:"Name",
 role:"Role",
 continuity_care:"CONTINUITY OF CARE",
 my_care_journey:"My Care Journey",
 active:"Active",
 registration_completed:"Registration completed",
 digital_triage_completed:"Digital triage completed",
 specialist_referral:"Specialist referral",
 specialist_consultation:"Specialist consultation",
 priority_green:"Priority: Green",
 awaiting_appointment:"Awaiting appointment",
 referral_tracking:"REFERRAL TRACKING",
 active_referral:"Active Referral",
 referred_to:"REFERRED TO",
 cardiology_consultation:"Cardiology consultation",
 wow_factor:"WOW FACTOR",
 call_emergency:"Call Emergency Services",
 patient_family_portal:"PATIENT & FAMILY PORTAL",
 connected_healthcare:"Connected Healthcare",
 patient_login:"Patient Login",
 registered_mobile:"Enter your registered mobile number",
 mobile_number:"Mobile Number",
 enter_mobile:"Enter mobile number",
 patient_id:"Patient ID",
 example_id:"Example: CB-10284",
 prototype_mode:"Prototype Mode",
 sim_auth:"This demonstration uses simulated authentication",
 track_referrals:"Track referrals",
 view_appointments:"View appointments",
 access_updates:"Access care updates",
 multilingual_support:"Multilingual support",
 authorized_access:"AUTHORIZED ACCESS",
 healthcare_staff_portal:"Healthcare Staff Portal",
 select_role:"Select your role to securely access the CareBridge healthcare coordination system.",
 field_health_worker:"FIELD HEALTH WORKER",
 clinical_access:"CLINICAL ACCESS",
 facility_operations_label:"FACILITY OPERATIONS",
 administrative_monitoring:"ADMINISTRATIVE MONITORING",
 secure_login:"Secure Login →",
 field_desc:"Patient registration, digital triage, referrals and follow-up.",
 doctor_desc_card:"Patient history, consultation, referrals and clinical review.",
 facility_desc_card:"Queue management, referrals, staff and facility operations.",
 district_desc_card:"Monitor facilities, referral delays, trends and district-level indicators.",
 authorized_healthcare:"AUTHORIZED HEALTHCARE ACCESS",
 secure_platform:"Secure access to the CareBridge healthcare coordination platform.",
 secure_role_access:"Secure role-based access",
 patient_continuity:"Patient information continuity",
 referral_coordination:"Referral and care coordination",
 facility_workflows:"Facility-level healthcare workflows",
 staff_login:"Staff Login",
 authorized_credentials:"Enter your authorized credentials to continue.",
 staff_id:"Staff ID",
 enter_staff_id:"Enter your Staff ID",
 password:"Password",
 enter_password:"Enter your password",
 demo_access:"DEMO ACCESS",
 demo_staff:"Use any Staff ID and password for this frontend prototype.",
 about:"About",
 features:"Features",
 care_journey:"Care Journey",
 hero_title:"No Patient Gets Lost in the Healthcare Journey.",
 hero_desc:"CareBridge connects patients, frontline health workers, doctors and healthcare facilities through one coordinated, closed-loop care journey — online or offline.",
 multilingual:"Multilingual",
 low_connectivity:"Low Connectivity",
 referral_tracking_label:"Referral Tracking",
 digital_triage_label:"Digital Triage",
 care_network:"CARE NETWORK",
 village:"Village",
 phc:"PHC",
 district:"District",
 system_operational:"System Operational",
 care_coordination:"24/7 Care Coordination",
 access_carebridge:"ACCESS CAREBRIDGE",
 choose_portal:"Choose your portal",
 secure_role_journey:"Secure access designed around your role in the healthcare journey.",
 for_patients:"FOR PATIENTS & FAMILIES",
 for_personnel:"FOR HEALTHCARE PERSONNEL",
 track_appointments:"Track appointments, referrals, consultations and your healthcare journey.",
 enter_patient_portal:"Enter Patient Portal →",
 access_records:"Access patient records, triage, referrals, queues and facility operations.",
 staff_login_link:"Staff Login →",
 core_capabilities:"CORE CAPABILITIES",
 requirements_title:"All 9 problem-statement requirements, plus 3 wow factors",
 teleconsultation:"Teleconsultation",
 teleconsultation_desc:"Request and confirm specialist consultations from the field.",
 appointment_queue:"Appointment & Queue",
 appointment_queue_desc:"Live queue management at every facility.",
 digital_triage:"Digital Triage",
 digital_triage_desc:"IMNCI-referenced Red/Yellow/Green priority assessment.",
 patient_records_feature:"Patient Records",
 patient_records_desc:"A longitudinal view of the patient's healthcare journey.",
 closed_loop_referrals:"Closed-Loop Referrals",
 closed_loop_desc:"Tracked from creation until the patient reaches completion.",
 diagnostic_coordination_feature:"Diagnostic Coordination",
 diagnostic_desc:"Track requested tests and their status.",
 medicine_availability_feature:"Medicine Availability",
 medicine_desc:"Real-time facility stock visibility.",
 high_risk_followup:"High-Risk Follow-up",
 high_risk_desc:"Flagged maternal, child and chronic cases, tracked to closure.",
 facility_dashboards:"Facility Dashboards",
 facility_dashboards_desc:"Operations, queue and staff attendance, facility-controlled.",
 offline_first:"Offline-First",
 offline_desc:"Core workflows work with zero connectivity, then auto-sync.",
 emergency_sos_feature:"Emergency SOS",
 emergency_desc:"Nearest-hospital lookup, coordinated with NHM 108/102.",
 whatsapp_status:"WhatsApp Status",
 whatsapp_desc:"Check a patient's referral status via a simple chat, no app needed.",
 ps_requirement:"PS REQUIREMENT",
 wow_factor_tag:"WOW FACTOR",
 the_care_journey:"THE CARE JOURNEY",
 first_to_completed:"From first contact to completed care",
 registration:"Registration",
 registration_desc:"Patient enters the care system.",
 triage:"Triage",
 triage_desc:"Priority is identified.",
 consultation:"Consultation",
 consultation_desc:"Doctor reviews the patient.",
 referral:"Referral",
 referral_desc:"Patient is tracked between facilities.",
 followup:"Follow-up",
 followup_desc:"Care continues until completion.",
 no_record:"No record found for this ID.",
 no_active_referral:"No active referral.",
 advance:"Advance →",
 in_stock:"In Stock",
 low_stock:"Low Stock",
 out_of_stock:"Out of Stock",
 refer_immediately:"Refer Immediately",
 danger_sign:"IMNCI danger sign present. Immediate clinical attention recommended.",
 monitor_closely:"Monitor Closely",
 clinical_review:"Clinical review should be prioritized.",
 routine_care:"Routine Care",
 no_danger:"No danger signs. Routine clinical assessment recommended."
},
hi:{
 brand_asha:"ASHA / ANM कार्यक्षेत्र",
 district_monitoring:"जिला स्वास्थ्य निगरानी",
 doctor_workspace:"डॉक्टर कार्यक्षेत्र",
 facility_admin:"संस्था प्रशासन",
 patient_portal_label:"रोगी पोर्टल",
 dashboard:"डैशबोर्ड",
 overview:"अवलोकन",
 facilities:"संस्थाएं",
 referral_network:"रेफरल नेटवर्क",
 alerts:"अलर्ट",
 trends:"रुझान",
 patient_queue:"रोगी कतार",
 patient_records:"रोगी रिकॉर्ड",
 diagnostics:"जांच",
 staff:"कर्मचारी",
 medicine:"दवा",
 reports:"रिपोर्ट",
 my_records:"मेरे रिकॉर्ड",
 appointments:"अपॉइंटमेंट",
 medicines:"दवाइयाँ",
 clinical_workspace:"क्लिनिकल कार्यक्षेत्र",
 doctor_dashboard:"डॉक्टर डैशबोर्ड",
 doctor_desc:"रोगियों, क्लिनिकल इतिहास और सक्रिय रेफरल की समीक्षा करें।",
 clinical_active:"क्लिनिकल सिस्टम सक्रिय",
 facility_operations:"संस्था संचालन",
 facility_desc:"संस्था संचालन का रियल-टाइम अवलोकन — संस्था व्यवस्थापक द्वारा नियंत्रित।",
 operational:"संचालित",
 district_health_monitoring:"जिला स्वास्थ्य निगरानी",
 district_desc:"जुड़ी हुई स्वास्थ्य संस्थाओं में स्वास्थ्य सेवा की निरंतरता की निगरानी करें।",
 network_operational:"नेटवर्क संचालित",
 patient_overview:"रोगी अवलोकन",
 patient_good_morning:"सुप्रभात, वैशाली",
 patient_desc:"आपकी वर्तमान स्वास्थ्य यात्रा का अवलोकन।",
 connected:"कनेक्टेड",
 connected_facilities:"जुड़ी हुई संस्थाएं",
 patients_today:"आज के रोगी",
 high_risk_cases:"उच्च जोखिम वाले मामले",
 across_district:"पूरे जिले में",
 across_facilities:"सभी संस्थाओं में",
 currently_tracked:"वर्तमान में ट्रैक किए जा रहे",
 under_monitoring:"निगरानी में",
 referral_completion:"रेफरल पूर्णता",
 followup_completion:"फॉलो-अप पूर्णता",
 triage_coverage:"ट्राइएज कवरेज",
 attention_required:"ध्यान आवश्यक",
 priority_alerts:"प्राथमिकता अलर्ट",
 waiting_patients:"प्रतीक्षारत रोगी",
 red_priority:"लाल प्राथमिकता",
 referrals:"रेफरल",
 completed:"पूर्ण",
 immediate_attention:"तत्काल ध्यान",
 consultations_today:"आज के परामर्श",
 active_today:"आज सक्रिय",
 clinical_queue:"क्लिनिकल कतार",
 patients_awaiting_review:"समीक्षा की प्रतीक्षा में रोगी",
 priority:"प्राथमिकता",
 reason:"कारण",
 open_record:"रिकॉर्ड खोलें",
 diagnostic_coordination:"जांच समन्वय",
 requested_tests:"अनुरोधित जांच",
 test:"जांच",
 status:"स्थिति",
 pending:"लंबित",
 in_progress:"प्रगति में",
 blood_cbc:"ब्लड CBC",
 xray_chest:"छाती का एक्स-रे",
 referral_management:"रेफरल प्रबंधन",
 active_referrals_closed:"सक्रिय रेफरल (क्लोज्ड-लूप)",
 active_queue:"सक्रिय कतार",
 patients_waiting:"प्रतीक्षारत रोगी",
 pending_referrals:"लंबित रेफरल",
 awaiting_completion:"पूर्णता की प्रतीक्षा",
 require_monitoring:"निगरानी आवश्यक",
 referral_status:"रेफरल स्थिति",
 sent:"भेजा गया",
 accepted:"स्वीकृत",
 arrived:"पहुंचा",
 completed_upper:"पूर्ण",
 facility_queue:"संस्था कतार",
 department_overview:"विभाग अवलोकन",
 department:"विभाग",
 waiting:"प्रतीक्षा",
 doctors:"डॉक्टर",
 normal:"सामान्य",
 busy:"व्यस्त",
 high_load:"उच्च भार",
 medicine_availability:"दवा उपलब्धता",
 facility_stock:"संस्था स्टॉक",
 qty:"मात्रा",
 facility_controlled:"संस्था-नियंत्रित",
 staff_roster:"कर्मचारी सूची और उपस्थिति",
 name:"नाम",
 role:"भूमिका",
 continuity_care:"देखभाल की निरंतरता",
 my_care_journey:"मेरी स्वास्थ्य यात्रा",
 active:"सक्रिय",
 registration_completed:"पंजीकरण पूर्ण",
 digital_triage_completed:"डिजिटल ट्राइएज पूर्ण",
 specialist_referral:"विशेषज्ञ रेफरल",
 specialist_consultation:"विशेषज्ञ परामर्श",
 priority_green:"प्राथमिकता: हरा",
 awaiting_appointment:"अपॉइंटमेंट की प्रतीक्षा",
 active_referral:"सक्रिय रेफरल",
 referred_to:"रेफर किया गया",
 cardiology_consultation:"कार्डियोलॉजी परामर्श",
 call_emergency:"आपातकालीन सेवाओं को कॉल करें",
 patient_family_portal:"रोगी और परिवार पोर्टल",
 connected_healthcare:"जुड़ी हुई स्वास्थ्य सेवा",
 patient_login:"रोगी लॉगिन",
 registered_mobile:"अपना पंजीकृत मोबाइल नंबर दर्ज करें",
 mobile_number:"मोबाइल नंबर",
 enter_mobile:"मोबाइल नंबर दर्ज करें",
 patient_id:"रोगी आईडी",
 example_id:"उदाहरण: CB-10284",
 prototype_mode:"प्रोटोटाइप मोड",
 sim_auth:"इस प्रदर्शन में सिम्युलेटेड प्रमाणीकरण का उपयोग किया गया है",
 track_referrals:"रेफरल ट्रैक करें",
 view_appointments:"अपॉइंटमेंट देखें",
 access_updates:"देखभाल अपडेट देखें",
 multilingual_support:"बहुभाषी सहायता",
 authorized_access:"अधिकृत एक्सेस",
 healthcare_staff_portal:"स्वास्थ्य कर्मचारी पोर्टल",
 select_role:"CareBridge स्वास्थ्य समन्वय प्रणाली तक सुरक्षित पहुंच के लिए अपनी भूमिका चुनें।",
 field_health_worker:"फील्ड स्वास्थ्य कार्यकर्ता",
 clinical_access:"क्लिनिकल एक्सेस",
 facility_operations_label:"संस्था संचालन",
 administrative_monitoring:"प्रशासनिक निगरानी",
 secure_login:"सुरक्षित लॉगिन →",
 field_desc:"रोगी पंजीकरण, डिजिटल ट्राइएज, रेफरल और फॉलो-अप।",
 doctor_desc_card:"रोगी इतिहास, परामर्श, रेफरल और क्लिनिकल समीक्षा।",
 facility_desc_card:"कतार प्रबंधन, रेफरल, कर्मचारी और संस्था संचालन।",
 district_desc_card:"संस्थाओं, रेफरल देरी, रुझानों और जिला-स्तरीय संकेतकों की निगरानी करें।",
 authorized_healthcare:"अधिकृत स्वास्थ्य एक्सेस",
 secure_platform:"CareBridge स्वास्थ्य समन्वय प्लेटफॉर्म तक सुरक्षित पहुंच।",
 secure_role_access:"भूमिका-आधारित सुरक्षित एक्सेस",
 patient_continuity:"रोगी जानकारी की निरंतरता",
 referral_coordination:"रेफरल और देखभाल समन्वय",
 facility_workflows:"संस्था-स्तरीय स्वास्थ्य कार्यप्रवाह",
 staff_login:"कर्मचारी लॉगिन",
 authorized_credentials:"जारी रखने के लिए अपने अधिकृत क्रेडेंशियल दर्ज करें।",
 staff_id:"कर्मचारी आईडी",
 enter_staff_id:"अपनी कर्मचारी आईडी दर्ज करें",
 password:"पासवर्ड",
 enter_password:"अपना पासवर्ड दर्ज करें",
 demo_access:"डेमो एक्सेस",
 demo_staff:"इस फ्रंटएंड प्रोटोटाइप के लिए कोई भी कर्मचारी आईडी और पासवर्ड उपयोग करें।",
 about:"परिचय",
 features:"विशेषताएं",
 care_journey:"स्वास्थ्य यात्रा",
 hero_title:"कोई भी रोगी स्वास्थ्य यात्रा में खो न जाए।",
 hero_desc:"CareBridge रोगियों, फ्रंटलाइन स्वास्थ्य कर्मियों, डॉक्टरों और स्वास्थ्य संस्थाओं को ऑनलाइन या ऑफलाइन एक समन्वित, क्लोज्ड-लूप स्वास्थ्य यात्रा से जोड़ता है।",
 multilingual:"बहुभाषी",
 low_connectivity:"कम कनेक्टिविटी",
 referral_tracking_label:"रेफरल ट्रैकिंग",
 digital_triage_label:"डिजिटल ट्राइएज",
 care_network:"स्वास्थ्य नेटवर्क",
 village:"गांव",
 phc:"PHC",
 district:"जिला",
 system_operational:"सिस्टम संचालित",
 care_coordination:"24/7 स्वास्थ्य समन्वय",
 access_carebridge:"CAREBRIDGE तक पहुंच",
 choose_portal:"अपना पोर्टल चुनें",
 secure_role_journey:"स्वास्थ्य यात्रा में आपकी भूमिका के अनुसार सुरक्षित पहुंच।",
 for_patients:"रोगियों और परिवारों के लिए",
 for_personnel:"स्वास्थ्य कर्मियों के लिए",
 track_appointments:"अपॉइंटमेंट, रेफरल, परामर्श और अपनी स्वास्थ्य यात्रा ट्रैक करें।",
 enter_patient_portal:"रोगी पोर्टल में प्रवेश →",
 access_records:"रोगी रिकॉर्ड, ट्राइएज, रेफरल, कतार और संस्था संचालन तक पहुंचें।",
 staff_login_link:"कर्मचारी लॉगिन →",
 core_capabilities:"मुख्य क्षमताएं",
 requirements_title:"सभी 9 समस्या-विवरण आवश्यकताएं और 3 अतिरिक्त विशेषताएं",
 teleconsultation:"टेलीपरामर्श",
 teleconsultation_desc:"फील्ड से विशेषज्ञ परामर्श का अनुरोध और पुष्टि करें।",
 appointment_queue:"अपॉइंटमेंट और कतार",
 appointment_queue_desc:"हर संस्था में लाइव कतार प्रबंधन।",
 digital_triage:"डिजिटल ट्राइएज",
 digital_triage_desc:"IMNCI-संदर्भित लाल/पीला/हरा प्राथमिकता मूल्यांकन।",
 patient_records_feature:"रोगी रिकॉर्ड",
 patient_records_desc:"रोगी की स्वास्थ्य यात्रा का दीर्घकालिक दृश्य।",
 closed_loop_referrals:"क्लोज्ड-लूप रेफरल",
 closed_loop_desc:"निर्माण से पूर्णता तक ट्रैक किया जाता है।",
 diagnostic_coordination_feature:"जांच समन्वय",
 diagnostic_desc:"अनुरोधित जांच और उनकी स्थिति ट्रैक करें।",
 medicine_availability_feature:"दवा उपलब्धता",
 medicine_desc:"संस्था में दवा स्टॉक की रियल-टाइम जानकारी।",
 high_risk_followup:"उच्च-जोखिम फॉलो-अप",
 high_risk_desc:"मातृ, बाल और दीर्घकालिक मामलों को पूर्णता तक ट्रैक करें।",
 facility_dashboards:"संस्था डैशबोर्ड",
 facility_dashboards_desc:"संचालन, कतार और कर्मचारी उपस्थिति का संस्था-नियंत्रित दृश्य।",
 offline_first:"ऑफलाइन-फर्स्ट",
 offline_desc:"मुख्य कार्यप्रवाह बिना कनेक्टिविटी के काम करते हैं और बाद में ऑटो-सिंक होते हैं।",
 emergency_sos_feature:"आपातकालीन SOS",
 emergency_desc:"निकटतम अस्पताल खोज, NHM 108/102 के साथ समन्वित।",
 whatsapp_status:"व्हाट्सऐप स्थिति",
 whatsapp_desc:"बिना ऐप के सरल चैट से रोगी की रेफरल स्थिति देखें।",
 ps_requirement:"PS आवश्यकता",
 wow_factor_tag:"विशेष सुविधा",
 the_care_journey:"स्वास्थ्य यात्रा",
 first_to_completed:"पहले संपर्क से पूर्ण देखभाल तक",
 registration:"पंजीकरण",
 registration_desc:"रोगी स्वास्थ्य प्रणाली में प्रवेश करता है।",
 triage:"ट्राइएज",
 triage_desc:"प्राथमिकता की पहचान की जाती है।",
 consultation:"परामर्श",
 consultation_desc:"डॉक्टर रोगी की समीक्षा करते हैं।",
 referral:"रेफरल",
 referral_desc:"रोगी को संस्थाओं के बीच ट्रैक किया जाता है।",
 followup:"फॉलो-अप",
 followup_desc:"देखभाल पूर्ण होने तक जारी रहती है।",
 no_record:"इस आईडी के लिए कोई रिकॉर्ड नहीं मिला।",
 no_active_referral:"कोई सक्रिय रेफरल नहीं।",
 advance:"आगे बढ़ें →",
 in_stock:"स्टॉक में",
 low_stock:"कम स्टॉक",
 out_of_stock:"स्टॉक समाप्त",
 refer_immediately:"तुरंत रेफर करें",
 danger_sign:"IMNCI का खतरे का संकेत मौजूद है। तत्काल चिकित्सकीय ध्यान आवश्यक है।",
 monitor_closely:"करीबी निगरानी",
 clinical_review:"क्लिनिकल समीक्षा को प्राथमिकता दी जानी चाहिए।",
 routine_care:"नियमित देखभाल",
 no_danger:"कोई खतरे के संकेत नहीं। नियमित क्लिनिकल मूल्यांकन की सलाह दी जाती है।",
 brand:"केअरब्रिज",
 online:"ऑनलाइन",
 offline:"ऑफलाइन",
 nav_about:"परिचय",
 nav_features:"विशेषताएं",
 nav_journey:"देखभाल यात्रा",
 patient_portal:"रोगी पोर्टल",
 staff_portal:"स्वास्थ्य कर्मचारी",
 sign_in:"सुरक्षित साइन इन →",
 continue_otp:"OTP से जारी रखें →",
 logout:"लॉगआउट",
 register_patient:"+ रोगी पंजीकरण",
 view_all:"सभी देखें",
 run_triage:"डिजिटल ट्राइएज चलाएं",
 check_risk:"जोखिम स्तर जांचें",
 mark_present:"उपस्थित करें",
 mark_absent:"अनुपस्थित करें",
 present:"उपस्थित",
 absent:"अनुपस्थित",
 send:"भेजें",
 emergency_sos:"🚨 आपातकालीन SOS",
 nearest_hospitals:"निकटतम अस्पताल",
 close:"बंद करें",
 whatsapp_title:"व्हाट्सऐप स्टेटस जांच",
 med_search_ph:"दवा खोजें...",
 footer_line:"स्वास्थ्य एवं परिवार कल्याण मंत्रालय · महाराष्ट्र सरकार (प्रोटोटाइप)",
 side_dashboard:"डैशबोर्ड",
 side_patients:"रोगी",
 side_triage:"ट्राइएज",
 side_referrals:"रेफरल",
 side_followups:"फॉलो-अप",
 stat_todaypatients:"आज के रोगी",
 stat_triagepending:"ट्राइएज लंबित",
 stat_activereferrals:"सक्रिय रेफरल",
 stat_followupsdue:"फॉलो-अप देय",
 sec_patientqueue:"रोगी कतार",
 sec_todaypatients:"आज के रोगी",
 sec_digitaltriage:"डिजिटल ट्राइएज",
 sec_quickassess:"त्वरित मूल्यांकन (IMNCI-आधारित)",
 sec_referraltracking:"रेफरल ट्रैकिंग",
 sec_closedloop:"क्लोज्ड-लूप रेफरल",
 col_patient:"रोगी",
 col_patientid:"रोगी आईडी",
 col_age:"आयु",
 col_triage:"ट्राइएज",
 col_action:"कार्रवाई",
 sym_breathing:"सांस लेने में कठिनाई",
 sym_chestpain:"गंभीर सीने में दर्द",
 sym_fever:"तेज़ बुखार",
 sym_headache:"हल्का सिरदर्द",
 field_ops:"क्षेत्रीय कार्य",
 good_morning:"सुप्रभात, सुनीता",
 manage_desc:"रोगी पंजीकरण, ट्राइएज और रेफरल प्रबंधित करें — ऑफ़लाइन काम करता है।",
 today:"Today",
 referral_tracking:"REFERRAL TRACKING",
 wow_factor:"WOW FACTOR"
},
mr:{
 brand_asha:"ASHA / ANM कार्यक्षेत्र",
 district_monitoring:"जिल्हा आरोग्य देखरेख",
 doctor_workspace:"डॉक्टर कार्यक्षेत्र",
 facility_admin:"आस्थापना प्रशासन",
 patient_portal_label:"रुग्ण पोर्टल",
 dashboard:"डॅशबोर्ड",
 overview:"आढावा",
 facilities:"आरोग्य आस्थापना",
 referral_network:"संदर्भ नेटवर्क",
 alerts:"सूचना",
 trends:"कल",
 patient_queue:"रुग्ण रांग",
 patient_records:"रुग्ण नोंदी",
 diagnostics:"तपासण्या",
 staff:"कर्मचारी",
 medicine:"औषधे",
 reports:"अहवाल",
 my_records:"माझ्या नोंदी",
 appointments:"भेटी",
 medicines:"औषधे",
 clinical_workspace:"वैद्यकीय कार्यक्षेत्र",
 doctor_dashboard:"डॉक्टर डॅशबोर्ड",
 doctor_desc:"रुग्ण, वैद्यकीय इतिहास आणि सक्रिय संदर्भांची पाहणी करा.",
 clinical_active:"वैद्यकीय प्रणाली सक्रिय",
 facility_operations:"आस्थापना कार्यकाज",
 facility_desc:"आस्थापनेच्या कार्यकाजाचा रिअल-टाइम आढावा — आस्थापना प्रशासकाच्या नियंत्रणाखाली.",
 operational:"कार्यरत",
 district_health_monitoring:"जिल्हा आरोग्य देखरेख",
 district_desc:"जोडलेल्या आरोग्य आस्थापनांमधील आरोग्यसेवेची सातत्यता पाहा.",
 network_operational:"नेटवर्क कार्यरत",
 patient_overview:"रुग्ण आढावा",
 patient_good_morning:"सुप्रभात, वैशाली",
 patient_desc:"तुमच्या सध्याच्या आरोग्य प्रवासाचा आढावा.",
 connected:"जोडलेले",
 connected_facilities:"जोडलेल्या आस्थापना",
 patients_today:"आजचे रुग्ण",
 high_risk_cases:"उच्च-जोखीम प्रकरणे",
 across_district:"संपूर्ण जिल्ह्यात",
 across_facilities:"सर्व आस्थापनांमध्ये",
 currently_tracked:"सध्या मागोवा घेतला जात आहे",
 under_monitoring:"देखरेखीखाली",
 referral_completion:"संदर्भ पूर्णता",
 followup_completion:"फॉलो-अप पूर्णता",
 triage_coverage:"ट्रायएज कव्हरेज",
 attention_required:"लक्ष आवश्यक",
 priority_alerts:"प्राधान्य सूचना",
 waiting_patients:"प्रतीक्षेत असलेले रुग्ण",
 red_priority:"लाल प्राधान्य",
 referrals:"संदर्भ",
 completed:"पूर्ण",
 immediate_attention:"तातडीचे लक्ष",
 consultations_today:"आजच्या तपासण्या",
 active_today:"आज सक्रिय",
 clinical_queue:"वैद्यकीय रांग",
 patients_awaiting_review:"तपासणीच्या प्रतीक्षेत रुग्ण",
 priority:"प्राधान्य",
 reason:"कारण",
 open_record:"नोंद उघडा",
 diagnostic_coordination:"तपासणी समन्वय",
 requested_tests:"विनंती केलेल्या तपासण्या",
 test:"तपासणी",
 status:"स्थिती",
 pending:"प्रलंबित",
 in_progress:"प्रगतीपथावर",
 blood_cbc:"रक्त CBC",
 xray_chest:"छातीचा एक्स-रे",
 referral_management:"संदर्भ व्यवस्थापन",
 active_referrals_closed:"सक्रिय संदर्भ (क्लोज्ड-लूप)",
 active_queue:"सक्रिय रांग",
 patients_waiting:"प्रतीक्षेत रुग्ण",
 pending_referrals:"प्रलंबित संदर्भ",
 awaiting_completion:"पूर्ण होण्याची प्रतीक्षा",
 require_monitoring:"देखरेख आवश्यक",
 referral_status:"संदर्भ स्थिती",
 sent:"पाठवले",
 accepted:"स्वीकृत",
 arrived:"पोहोचले",
 completed_upper:"पूर्ण",
 facility_queue:"आस्थापना रांग",
 department_overview:"विभागाचा आढावा",
 department:"विभाग",
 waiting:"प्रतीक्षा",
 doctors:"डॉक्टर",
 normal:"सामान्य",
 busy:"व्यस्त",
 high_load:"जास्त भार",
 medicine_availability:"औषध उपलब्धता",
 facility_stock:"आस्थापना साठा",
 qty:"प्रमाण",
 facility_controlled:"आस्थापना-नियंत्रित",
 staff_roster:"कर्मचारी यादी व उपस्थिती",
 name:"नाव",
 role:"भूमिका",
 continuity_care:"सातत्यपूर्ण आरोग्यसेवा",
 my_care_journey:"माझा आरोग्य प्रवास",
 active:"सक्रिय",
 registration_completed:"नोंदणी पूर्ण",
 digital_triage_completed:"डिजिटल ट्रायएज पूर्ण",
 specialist_referral:"तज्ज्ञ संदर्भ",
 specialist_consultation:"तज्ज्ञ सल्ला",
 priority_green:"प्राधान्य: हिरवा",
 awaiting_appointment:"भेटीची प्रतीक्षा",
 active_referral:"सक्रिय संदर्भ",
 referred_to:"संदर्भित ठिकाण",
 cardiology_consultation:"हृदयरोग तज्ज्ञांचा सल्ला",
 call_emergency:"आपत्कालीन सेवांना कॉल करा",
 patient_family_portal:"रुग्ण व कुटुंब पोर्टल",
 connected_healthcare:"जोडलेली आरोग्यसेवा",
 patient_login:"रुग्ण लॉगिन",
 registered_mobile:"तुमचा नोंदणीकृत मोबाईल क्रमांक टाका",
 mobile_number:"मोबाईल क्रमांक",
 enter_mobile:"मोबाईल क्रमांक टाका",
 patient_id:"रुग्ण आयडी",
 example_id:"उदाहरण: CB-10284",
 prototype_mode:"प्रोटोटाइप मोड",
 sim_auth:"या प्रात्यक्षिकात सिम्युलेटेड प्रमाणीकरण वापरले आहे",
 track_referrals:"संदर्भांचा मागोवा घ्या",
 view_appointments:"भेटी पाहा",
 access_updates:"आरोग्यसेवा अपडेट्स पाहा",
 multilingual_support:"बहुभाषिक सुविधा",
 authorized_access:"अधिकृत प्रवेश",
 healthcare_staff_portal:"आरोग्य कर्मचारी पोर्टल",
 select_role:"CareBridge आरोग्य समन्वय प्रणालीमध्ये सुरक्षित प्रवेशासाठी तुमची भूमिका निवडा.",
 field_health_worker:"क्षेत्रीय आरोग्य कर्मचारी",
 clinical_access:"वैद्यकीय प्रवेश",
 facility_operations_label:"आस्थापना कार्यकाज",
 administrative_monitoring:"प्रशासकीय देखरेख",
 secure_login:"सुरक्षित लॉगिन →",
 field_desc:"रुग्ण नोंदणी, डिजिटल ट्रायएज, संदर्भ आणि फॉलो-अप.",
 doctor_desc_card:"रुग्ण इतिहास, सल्ला, संदर्भ आणि वैद्यकीय पाहणी.",
 facility_desc_card:"रांग व्यवस्थापन, संदर्भ, कर्मचारी आणि आस्थापना कार्यकाज.",
 district_desc_card:"आस्थापना, संदर्भातील विलंब, कल आणि जिल्हास्तरीय निर्देशांकांचे निरीक्षण करा.",
 authorized_healthcare:"अधिकृत आरोग्य प्रवेश",
 secure_platform:"CareBridge आरोग्य समन्वय प्लॅटफॉर्ममध्ये सुरक्षित प्रवेश.",
 secure_role_access:"भूमिकेनुसार सुरक्षित प्रवेश",
 patient_continuity:"रुग्ण माहितीची सातत्यता",
 referral_coordination:"संदर्भ व आरोग्यसेवा समन्वय",
 facility_workflows:"आस्थापना-स्तरीय आरोग्य कार्यप्रवाह",
 staff_login:"कर्मचारी लॉगिन",
 authorized_credentials:"पुढे जाण्यासाठी अधिकृत क्रेडेन्शियल्स टाका.",
 staff_id:"कर्मचारी आयडी",
 enter_staff_id:"कर्मचारी आयडी टाका",
 password:"पासवर्ड",
 enter_password:"पासवर्ड टाका",
 demo_access:"डेमो प्रवेश",
 demo_staff:"या फ्रंटएंड प्रोटोटाइपसाठी कोणताही कर्मचारी आयडी आणि पासवर्ड वापरा.",
 about:"परिचय",
 features:"वैशिष्ट्ये",
 care_journey:"आरोग्य प्रवास",
 hero_title:"कोणताही रुग्ण आरोग्यसेवेच्या प्रवासात हरवू नये.",
 hero_desc:"CareBridge रुग्ण, क्षेत्रीय आरोग्य कर्मचारी, डॉक्टर आणि आरोग्य आस्थापनांना ऑनलाइन किंवा ऑफलाइन एका समन्वित, क्लोज्ड-लूप आरोग्य प्रवासाशी जोडते.",
 multilingual:"बहुभाषिक",
 low_connectivity:"कमी कनेक्टिव्हिटी",
 referral_tracking_label:"संदर्भ ट्रॅकिंग",
 digital_triage_label:"डिजिटल ट्रायएज",
 care_network:"आरोग्य नेटवर्क",
 village:"गाव",
 phc:"PHC",
 district:"जिल्हा",
 system_operational:"प्रणाली कार्यरत",
 care_coordination:"२४/७ आरोग्य समन्वय",
 access_carebridge:"CAREBRIDGE प्रवेश",
 choose_portal:"तुमचे पोर्टल निवडा",
 secure_role_journey:"आरोग्य प्रवासातील तुमच्या भूमिकेनुसार सुरक्षित प्रवेश.",
 for_patients:"रुग्ण आणि कुटुंबांसाठी",
 for_personnel:"आरोग्य कर्मचाऱ्यांसाठी",
 track_appointments:"भेटी, संदर्भ, सल्लामसलत आणि तुमच्या आरोग्य प्रवासाचा मागोवा घ्या.",
 enter_patient_portal:"रुग्ण पोर्टलमध्ये प्रवेश →",
 access_records:"रुग्ण नोंदी, ट्रायएज, संदर्भ, रांगा आणि आस्थापना कार्यकाजात प्रवेश करा.",
 staff_login_link:"कर्मचारी लॉगिन →",
 core_capabilities:"मुख्य क्षमता",
 requirements_title:"सर्व ९ समस्या-विधान आवश्यकता आणि ३ अतिरिक्त वैशिष्ट्ये",
 teleconsultation:"दूरस्थ वैद्यकीय सल्ला",
 teleconsultation_desc:"क्षेत्रातून तज्ज्ञ सल्ल्याची विनंती व पुष्टी करा.",
 appointment_queue:"भेट व रांग",
 appointment_queue_desc:"प्रत्येक आस्थापनेतील लाइव्ह रांग व्यवस्थापन.",
 digital_triage:"डिजिटल ट्रायएज",
 digital_triage_desc:"IMNCI-संदर्भित लाल/पिवळा/हिरवा प्राधान्य मूल्यांकन.",
 patient_records_feature:"रुग्ण नोंदी",
 patient_records_desc:"रुग्णाच्या आरोग्य प्रवासाचा दीर्घकालीन आढावा.",
 closed_loop_referrals:"क्लोज्ड-लूप संदर्भ",
 closed_loop_desc:"निर्मितीपासून पूर्णतेपर्यंत मागोवा घेतला जातो.",
 diagnostic_coordination_feature:"तपासणी समन्वय",
 diagnostic_desc:"विनंती केलेल्या तपासण्या व त्यांची स्थिती पाहा.",
 medicine_availability_feature:"औषध उपलब्धता",
 medicine_desc:"आस्थापनेतील औषध साठ्याची रिअल-टाइम माहिती.",
 high_risk_followup:"उच्च-जोखीम फॉलो-अप",
 high_risk_desc:"माता, बालक आणि दीर्घकालीन प्रकरणांचा पूर्णतेपर्यंत मागोवा.",
 facility_dashboards:"आस्थापना डॅशबोर्ड",
 facility_dashboards_desc:"कार्यकाज, रांग आणि कर्मचारी उपस्थितीचा आस्थापना-नियंत्रित आढावा.",
 offline_first:"ऑफलाइन-फर्स्ट",
 offline_desc:"मुख्य कार्यप्रवाह कनेक्टिव्हिटी नसतानाही चालतात आणि नंतर ऑटो-सिंक होतात.",
 emergency_sos_feature:"आपत्कालीन SOS",
 emergency_desc:"जवळचे रुग्णालय शोधणे, NHM 108/102 सोबत समन्वयित.",
 whatsapp_status:"व्हॉट्सअ‍ॅप स्थिती",
 whatsapp_desc:"अॅपशिवाय साध्या चॅटद्वारे रुग्णाच्या संदर्भाची स्थिती पाहा.",
 ps_requirement:"PS आवश्यकता",
 wow_factor_tag:"अतिरिक्त वैशिष्ट्य",
 the_care_journey:"आरोग्य प्रवास",
 first_to_completed:"पहिल्या संपर्कापासून पूर्ण उपचारापर्यंत",
 registration:"नोंदणी",
 registration_desc:"रुग्ण आरोग्य व्यवस्थेत प्रवेश करतो.",
 triage:"ट्रायएज",
 triage_desc:"प्राधान्य निश्चित केले जाते.",
 consultation:"सल्लामसलत",
 consultation_desc:"डॉक्टर रुग्णाची पाहणी करतात.",
 referral:"संदर्भ",
 referral_desc:"रुग्णाचा आस्थापनांदरम्यान मागोवा घेतला जातो.",
 followup:"फॉलो-अप",
 followup_desc:"पूर्ण उपचार होईपर्यंत सेवा सुरू राहते.",
 no_record:"या आयडीसाठी कोणतीही नोंद सापडली नाही.",
 no_active_referral:"कोणताही सक्रिय संदर्भ नाही.",
 advance:"पुढे जा →",
 in_stock:"साठ्यात उपलब्ध",
 low_stock:"कमी साठा",
 out_of_stock:"साठा संपला",
 refer_immediately:"तातडीने संदर्भित करा",
 danger_sign:"IMNCI मधील धोक्याची खूण आढळली. तातडीने वैद्यकीय लक्ष आवश्यक आहे.",
 monitor_closely:"जवळून निरीक्षण करा",
 clinical_review:"वैद्यकीय पाहणीला प्राधान्य द्यावे.",
 routine_care:"नियमित सेवा",
 no_danger:"धोक्याची कोणतीही खूण नाही. नियमित वैद्यकीय मूल्यांकनाची शिफारस केली जाते.",
 brand:"केअरब्रिज",
 online:"ऑनलाइन",
 offline:"ऑफलाइन",
 nav_about:"परिचय",
 nav_features:"वैशिष्ट्ये",
 nav_journey:"आरोग्य प्रवास",
 patient_portal:"रुग्ण पोर्टल",
 staff_portal:"आरोग्य कर्मचारी",
 sign_in:"सुरक्षित साइन इन →",
 continue_otp:"OTP ने सुरू ठेवा →",
 logout:"लॉगआउट",
 register_patient:"+ रुग्ण नोंदणी",
 view_all:"सर्व पाहा",
 run_triage:"डिजिटल ट्रायएज चालवा",
 check_risk:"जोखीम पातळी तपासा",
 mark_present:"उपस्थित करा",
 mark_absent:"अनुपस्थित करा",
 present:"उपस्थित",
 absent:"अनुपस्थित",
 send:"पाठवा",
 emergency_sos:"🚨 आणीबाणी SOS",
 nearest_hospitals:"जवळची रुग्णालये",
 close:"बंद करा",
 whatsapp_title:"व्हॉट्सअ‍ॅप स्थिती तपासणी",
 med_search_ph:"औषध शोधा...",
 footer_line:"आरोग्य व कुटुंब कल्याण मंत्रालय · महाराष्ट्र शासन (प्रोटोटाइप)",
 side_dashboard:"डॅशबोर्ड",
 side_patients:"रुग्ण",
 side_triage:"ट्रायएज",
 side_referrals:"संदर्भ",
 side_followups:"फॉलो-अप",
 stat_todaypatients:"आजचे रुग्ण",
 stat_triagepending:"ट्रायएज प्रलंबित",
 stat_activereferrals:"सक्रिय संदर्भ",
 stat_followupsdue:"फॉलो-अप देय",
 sec_patientqueue:"रुग्ण रांग",
 sec_todaypatients:"आजचे रुग्ण",
 sec_digitaltriage:"डिजिटल ट्रायएज",
 sec_quickassess:"जलद मूल्यांकन (IMNCI-आधारित)",
 sec_referraltracking:"संदर्भ ट्रॅकिंग",
 sec_closedloop:"क्लोज्ड-लूप संदर्भ",
 col_patient:"रुग्ण",
 col_patientid:"रुग्ण आयडी",
 col_age:"वय",
 col_triage:"ट्रायएज",
 col_action:"कृती",
 sym_breathing:"श्वास घेण्यास त्रास",
 sym_chestpain:"तीव्र छातीत दुखणे",
 sym_fever:"तीव्र ताप",
 sym_headache:"सौम्य डोकेदुखी",
 field_ops:"क्षेत्रीय कामकाज",
 good_morning:"सुप्रभात, सुनीता",
 manage_desc:"रुग्ण नोंदणी, ट्रायएज आणि संदर्भ व्यवस्थापित करा — ऑफलाइन काम करते.",
 today:"Today",
 referral_tracking:"REFERRAL TRACKING",
 wow_factor:"WOW FACTOR"
}
};

let lang = localStorage.getItem('cbLang') || 'en';

function applyLanguage(l){
 lang = l || lang;
 localStorage.setItem('cbLang', lang);
 document.querySelectorAll('.langBtn').forEach(b=>b.classList.toggle('active', b.dataset.lang===lang));
 document.querySelectorAll('[data-i18n]').forEach(e=>{
   const k=e.dataset.i18n; if(T[lang][k]!==undefined) e.textContent=T[lang][k];
 });
 document.querySelectorAll('[data-i18n-placeholder]').forEach(e=>{
   const k=e.dataset.i18nPlaceholder; if(T[lang][k]!==undefined) e.placeholder=T[lang][k];
 });
}

/* ===== SAMPLE DATA (shared across dashboards) ===== */
const patients=[
 {id:'CB-10421',name:'Suresh Patil',age:47,triage:'red'},
 {id:'CB-10422',name:'Asha Shinde',age:34,triage:'yellow'},
 {id:'CB-10423',name:'Rohit Jadhav',age:28,triage:'green'}
];
const STEP_SEQ=['sent','accepted','arrived','completed_upper'];
let referrals=[{id:'CB-10392',patient:'Suresh Patil',dept:'Cardiology',cur:1},{id:'CB-10388',patient:'Asha Shinde',dept:'Neurology',cur:2}];
const medicines=[{name:'Paracetamol',qty:120,status:'ok'},{name:'ORS Sachets',qty:8,status:'low'},{name:'Iron Folic Acid',qty:0,status:'out'},{name:'Amoxicillin',qty:60,status:'ok'}];
let staff=[{name:'Sunita Pawar',role:'ASHA Worker',present:true},{name:'Mangal Shinde',role:'ANM',present:true},{name:'Dr. Kavita Deshmukh',role:'Medical Officer',present:false}];
const sosHospitals=[{name:'District Civil Hospital',dist:'6.2 km',phone:'02112-XXXXXX'},{name:'Rural Hospital Baramati',dist:'3.4 km',phone:'02112-YYYYYY'}];

/* ===== OFFLINE TOGGLE ===== */
let online=true;
function toggleOffline(){
 online=!online;
 const b=document.getElementById('offlineBadge');
 if(!b)return;
 b.classList.toggle('off',!online);
 b.innerHTML=(online?'🟢 ':'🔴 ')+'<span data-i18n="'+(online?'online':'offline')+'">'+T[lang][online?'online':'offline']+'</span>';
}

/* ===== TRIAGE (ASHA dashboard) ===== */
function runTriage(){
 const symptoms=document.querySelectorAll('.symptom-checkbox:checked');
 const result=document.getElementById('triageResult');
 if(!result)return;
 if(symptoms.length>=3) result.innerHTML=`<div class="triage red-result"><strong>🔴 RED — ${T[lang].refer_immediately}</strong><p>${T[lang].danger_sign}</p></div>`;
 else if(symptoms.length===2) result.innerHTML=`<div class="triage yellow-result"><strong>🟡 YELLOW — ${T[lang].monitor_closely}</strong><p>${T[lang].clinical_review}</p></div>`;
 else result.innerHTML=`<div class="triage green-result"><strong>🟢 GREEN — ${T[lang].routine_care}</strong><p>${T[lang].no_danger}</p></div>`;
}

/* ===== REFERRAL TRACKER (advance step) ===== */
function advanceReferral(id){
 const r=referrals.find(x=>x.id===id);
 if(r && r.cur<STEP_SEQ.length-1){ r.cur++; renderReferralGrid(); }
}
function renderReferralGrid(){
 const wrap=document.getElementById('referralGrid');
 if(!wrap)return;
 wrap.innerHTML='';
 referrals.forEach(r=>{
  const pillClass=r.cur===STEP_SEQ.length-1?'green-pill':(r.cur>=1?'yellow-pill':'blue-pill');
  const div=document.createElement('div');
  div.className='referral-mini';
  div.innerHTML=`<strong>${r.id}</strong><h3>${r.dept}</h3><p>${r.patient}</p><span class="${pillClass}">${STEP_SEQ[r.cur]}</span>`;
  if(r.cur<STEP_SEQ.length-1){
    const btn=document.createElement('button');
    btn.className='table-button'; btn.style.marginTop='.5rem'; btn.textContent=T[lang].advance;
    btn.onclick=()=>advanceReferral(r.id);
    div.appendChild(btn);
  }
  wrap.appendChild(div);
 });
}

/* ===== STAFF ATTENDANCE (Facility dashboard) ===== */
function renderStaff(){
 const body=document.getElementById('staffBody');
 if(!body)return;
 body.innerHTML='';
 staff.forEach((s,i)=>{
  const tr=document.createElement('tr');
  const pill=s.present?'green-pill':'red-pill';
  const label=s.present?T[lang].present:T[lang].absent;
  const btnLabel=s.present?T[lang].mark_absent:T[lang].mark_present;
  tr.innerHTML=`<td><strong>${s.name}</strong></td><td>${s.role}</td><td><span class="${pill}">${label}</span></td><td></td>`;
  const btn=document.createElement('button');
  btn.className='staff-toggle'; btn.textContent=btnLabel;
  btn.onclick=()=>{staff[i].present=!staff[i].present; renderStaff();};
  tr.lastElementChild.appendChild(btn);
  body.appendChild(tr);
 });
}

/* ===== MEDICINE SEARCH (Facility dashboard) ===== */
function renderMed(){
 const input=document.getElementById('medSearch');
 const body=document.getElementById('medBody');
 if(!body)return;
 const q=(input?input.value:'').toLowerCase();
 body.innerHTML='';
 medicines.filter(m=>m.name.toLowerCase().includes(q)).forEach(m=>{
  const cls=m.status==='ok'?'green-pill':(m.status==='low'?'yellow-pill':'red-pill');
  const label=m.status==='ok'?T[lang].in_stock:(m.status==='low'?T[lang].low_stock:T[lang].out_of_stock);
  const tr=document.createElement('tr');
  tr.innerHTML=`<td>${m.name}</td><td>${m.qty}</td><td><span class="${cls}">${label}</span></td>`;
  body.appendChild(tr);
 });
}

/* ===== WHATSAPP STATUS CHECK ===== */
function sendChat(){
 const inp=document.getElementById('chatInput');
 const log=document.getElementById('chatLog');
 if(!inp||!log)return;
 const id=inp.value.trim().toUpperCase();
 if(!id)return;
 const um=document.createElement('div'); um.className='chat-msg out'; um.textContent=id; log.appendChild(um);
 const p=patients.find(x=>x.id===id);
 const ref=referrals.find(r=>p && r.patient===p.name);
 let reply;
 if(!p) reply=T[lang].no_record;
 else if(ref) reply=p.name+': '+T[lang][STEP_SEQ[ref.cur]];
 else reply=p.name+': '+T[lang].no_active_referral;
 const bm=document.createElement('div'); bm.className='chat-msg in'; bm.textContent=reply; log.appendChild(bm);
 inp.value=''; log.scrollTop=log.scrollHeight;
}

/* ===== SOS MODAL ===== */
function triggerSOS(){
 const modal=document.getElementById('sosModal');
 const body=document.getElementById('sosBody');
 if(body){
   body.innerHTML='';
   sosHospitals.forEach(h=>{
    const div=document.createElement('div'); div.className='sos-hospital';
    div.innerHTML=`<b>${h.name}</b><br>${h.dist} · ${h.phone}`;
    body.appendChild(div);
   });
 }
 if(modal) modal.classList.add('show');
}
function closeModal(){ document.querySelectorAll('.modal').forEach(m=>m.classList.remove('show')); }

/* ===== NAV / AUTH HELPERS ===== */
function demoLogin(role){ localStorage.setItem('carebridgeRole', role); }
function logout(){ localStorage.removeItem('carebridgeRole'); window.location.href='../index.html'; }
function goTo(page){ window.location.href=page; }
function addQueue(){
 const tok=document.getElementById('queueBody');
 if(!tok)return;
 const tr=document.createElement('tr');
 tr.innerHTML=`<td>A${14+tok.children.length}</td><td>New Patient</td><td><span class="yellow-pill">Waiting</span></td>`;
 tok.appendChild(tr);
}

document.addEventListener('DOMContentLoaded',()=>{
 document.querySelectorAll('.langBtn').forEach(b=>{ b.onclick=()=>applyLanguage(b.dataset.lang); });
 applyLanguage(lang);
 renderReferralGrid();
 renderStaff();
 renderMed();
});
